#!/bin/bash

sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list
apt-get update
apt-get install -y build-essential software-properties-common curl default-jdk ffmpeg libavcodec-extra
apt-get clean

curl -L -o /tmp/sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
dpkg -i /tmp/sbt-$SBT_VERSION.deb
rm /tmp/sbt-$SBT_VERSION.deb
